import type { AmplexusProduct } from "@/types/product";

export const products: AmplexusProduct[] = [
  {
    handle: "self-care-journal",
    title: "Daily Self-Care Journal",
    price: 24.99,
    category: "journals-planners",
    shopifyProductId: "placeholder-id-1",
    summary: "A guided journal for daily reflection and self-care practices.",
    detail: "This beautifully designed journal helps you track your mental wellness journey with prompts for gratitude, mood tracking, and intentional reflection.",
    imageUrl: "/products/journal-placeholder.jpg",
    benefits: [
      "Daily prompts for mindfulness",
      "Mood tracking pages",
      "Weekly reflection sections",
      "High-quality paper",
    ],
    care: "Keep in a dry place. Use acid-free pens for longevity.",
    tags: ["new", "popular"],
  },
  {
    handle: "calm-tee",
    title: "Calm Mind T-Shirt",
    price: 29.99,
    category: "apparel",
    shopifyProductId: "placeholder-id-2",
    summary: "Comfortable tee with a gentle reminder to breathe and stay grounded.",
    detail: "Made from soft, sustainable cotton, this t-shirt features a minimalist design that reminds you to prioritize your mental wellness.",
    imageUrl: "/products/tshirt-placeholder.jpg",
    benefits: [
      "100% organic cotton",
      "Unisex fit",
      "Ethically sourced",
      "Machine washable",
    ],
    care: "Machine wash cold, tumble dry low. Do not bleach.",
    tags: ["apparel", "popular"],
  },
  {
    handle: "morning-ritual-mug",
    title: "Morning Ritual Ceramic Mug",
    price: 18.99,
    category: "mugs-drinkware",
    shopifyProductId: "placeholder-id-3",
    summary: "Start your day with intention using this mindful morning mug.",
    detail: "A beautifully crafted ceramic mug designed to make your morning routine a moment of self-care.",
    imageUrl: "/products/mug-placeholder.jpg",
    benefits: [
      "14oz capacity",
      "Microwave and dishwasher safe",
      "Lead-free ceramic",
      "Comfortable handle",
    ],
    care: "Dishwasher safe. Avoid sudden temperature changes.",
  },
  {
    handle: "self-care-essentials-box",
    title: "Self-Care Essentials Box",
    price: 59.99,
    category: "self-care-boxes",
    shopifyProductId: "placeholder-id-4",
    summary: "A curated collection of tools to support your mental wellness journey.",
    detail: "This thoughtfully assembled box includes a journal, soothing tea, aromatherapy items, and guided exercises to help you prioritize self-care.",
    imageUrl: "/products/box-placeholder.jpg",
    benefits: [
      "Journal + pen set",
      "Calming tea blend",
      "Aromatherapy sachet",
      "Guided meditation cards",
    ],
    tags: ["new", "gift"],
  },
];
